# Generated by Django 2.1.1 on 2018-09-04 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('importdata', '0004_auto_20180904_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='igdbgame',
            name='genres',
        ),
    ]
