# Generated by Django 2.1.1 on 2018-09-04 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('importdata', '0005_remove_igdbgame_genres'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IGDBGame',
            new_name='IGDBGameData',
        ),
    ]
