# Generated by Django 2.1.1 on 2018-09-04 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('importdata', '0006_auto_20180904_1811'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IGDBGameData',
            new_name='IGDBGame',
        ),
    ]
