# Generated by Django 2.1.1 on 2018-09-04 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('importdata', '0007_auto_20180904_1813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='igdbgame',
            name='time_to_beat',
        ),
    ]
