# Generated by Django 2.1.1 on 2018-09-04 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importdata', '0008_remove_igdbgame_time_to_beat'),
    ]

    operations = [
        migrations.AddField(
            model_name='igdbgame',
            name='time_to_beat',
            field=models.FloatField(help_text='Avarage time to beat the game', null=True, verbose_name='Time To Beat'),
        ),
    ]
