# Generated by Django 2.1.1 on 2018-09-05 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importdata', '0010_igdbgame_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='igdbgame',
            name='genres',
            field=models.ManyToManyField(blank=True, to='importdata.Genre'),
        ),
    ]
