# Generated by Django 2.1.1 on 2018-09-06 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importdata', '0011_auto_20180905_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='igdbgame',
            name='steam',
            field=models.IntegerField(null=True, verbose_name='Steam ID'),
        ),
    ]
